services:

  mysql:
    image: mysql:8.0
    container_name: credit_card_mysql
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  django:
    build: .
    container_name: credit_card_django
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      mysql:
        condition: service_healthy

  fastapi:
    build: .
    container_name: credit_card_fastapi
    restart: unless-stopped
    command: uvicorn payment_api.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: